sudo: false

addons:
  apt_packages:
    - lib32stdc++6

before_script:
  - wget http://www.sourcemod.net/smdrop/1.8/sourcemod-1.8.0-git5450-linux.tar.gz
  - tar -xzf sourcemod-1.8.0-git5450-linux.tar.gz
  - chmod +rx addons/sourcemod/scripting/spcomp
  - cd addons/sourcemod/scripting/
  
script:
  - ./spcomp multicolors_example.sp

notifications:
  email: 
    recipients:
      - webmaster@bara.in
    on_success: always
    on_failure: always
